language: android

# Required to run retrolambda
jdk:
    - oraclejdk8
  
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository  
script
    - ./gradlew clean build
deploy:
    provider: script
    script: ./gradlew bintrayUpload
    on:
        branch: master  
