language: android

# Required to run retrolambda
jdk:
    - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    # RS components
    - build-tools-23.0.2
    - android-23
script:
    - ./gradlew clean build
#TODO: reenable artifact deployment
#deploy:
#    provider: script
#    script: ./gradlew bintrayUpload
#    on:
#        branch: master
